object frmPlatforms: TfrmPlatforms
  Left = 0
  Top = 0
  BorderIcons = []
  BorderStyle = bsSingle
  Caption = 'frmPlatforms'
  ClientHeight = 913
  ClientWidth = 1551
  Color = 2499101
  DoubleBuffered = True
  ParentFont = True
  FormStyle = fsMDIChild
  OldCreateOrder = False
  Visible = True
  WindowState = wsMaximized
  OnActivate = FormActivate
  PixelsPerInch = 96
  TextHeight = 13
end
