object frmOther: TfrmOther
  Left = 0
  Top = 0
  BorderIcons = []
  BorderStyle = bsNone
  Caption = 'frmOther'
  ClientHeight = 201
  ClientWidth = 447
  Color = clBtnFace
  DoubleBuffered = True
  ParentFont = True
  FormStyle = fsMDIChild
  OldCreateOrder = False
  Visible = True
  WindowState = wsMaximized
  OnActivate = FormActivate
  PixelsPerInch = 96
  TextHeight = 13
end
