object frmRight: TfrmRight
  Left = 0
  Top = 0
  Align = alRight
  BorderStyle = bsNone
  Caption = 'frmRight'
  ClientHeight = 870
  ClientWidth = 120
  Color = clCream
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object pnlContainer: TPanel
    Left = 0
    Top = 0
    Width = 120
    Height = 870
    Align = alClient
    BevelOuter = bvNone
    Color = clSkyBlue
    ParentBackground = False
    TabOrder = 0
    ExplicitWidth = 150
    ExplicitHeight = 543
  end
end
