object frmRight: TfrmRight
  Left = 0
  Top = 0
  BorderStyle = bsNone
  Caption = 'frmRight'
  ClientHeight = 543
  ClientWidth = 166
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object pnlContainer: TPanel
    Left = 0
    Top = 41
    Width = 166
    Height = 502
    Align = alClient
    BevelOuter = bvNone
    Color = 141979
    ParentBackground = False
    TabOrder = 0
    ExplicitWidth = 150
    ExplicitHeight = 463
  end
  object pnlTitle: TPanel
    Left = 0
    Top = 0
    Width = 166
    Height = 41
    Align = alTop
    BevelOuter = bvNone
    Color = 5532607
    Font.Charset = DEFAULT_CHARSET
    Font.Color = 15659247
    Font.Height = -20
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 1
    ExplicitWidth = 150
    object lblTitle: TLabel
      Left = 0
      Top = 0
      Width = 166
      Height = 41
      Align = alClient
      Alignment = taCenter
      AutoSize = False
      Caption = 'TITLE'
      Layout = tlCenter
      WordWrap = True
      ExplicitLeft = 72
      ExplicitTop = 8
      ExplicitWidth = 59
      ExplicitHeight = 24
    end
  end
end
