object frmMissileResourceAllocationPickList: TfrmMissileResourceAllocationPickList
  Left = 0
  Top = 0
  BorderIcons = []
  BorderStyle = bsSingle
  Caption = ' Missile Resource Allocation'
  ClientHeight = 639
  ClientWidth = 754
  Color = clBtnShadow
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -12
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 14
  object pnlMain: TPanel
    Left = 0
    Top = 0
    Width = 754
    Height = 639
    Align = alClient
    BevelOuter = bvNone
    BorderWidth = 10
    Color = 2499101
    ParentBackground = False
    TabOrder = 0
    ExplicitWidth = 621
    ExplicitHeight = 352
    object lbl1: TLabel
      Left = 12
      Top = 544
      Width = 62
      Height = 21
      Caption = 'Search :'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWhite
      Font.Height = -21
      Font.Name = 'Deusex'
      Font.Style = []
      ParentFont = False
    end
    object btnAdd: TButton
      Left = 337
      Top = 263
      Width = 80
      Height = 30
      Caption = 'Add'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 0
      OnClick = btnAddClick
    end
    object btnRemove: TButton
      Left = 337
      Top = 303
      Width = 80
      Height = 30
      Caption = 'Remove'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 1
      OnClick = btnRemoveClick
    end
    object lbAllMissileDef: TListBox
      Left = 12
      Top = 62
      Width = 313
      Height = 474
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 2
      OnClick = lbAllMissileDefClick
      OnDblClick = btnAddClick
    end
    object lbAllMissileOnRA: TListBox
      Left = 430
      Top = 62
      Width = 313
      Height = 474
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 3
      OnClick = lbAllMissileOnRAClick
      OnDblClick = btnRemoveClick
    end
    object btnClose: TButton
      Left = 663
      Top = 599
      Width = 80
      Height = 30
      Caption = 'Close'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 4
      OnClick = btnCloseClick
    end
    object edtSearch: TEdit
      Left = 78
      Top = 542
      Width = 247
      Height = 25
      AutoSize = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 5
      OnKeyPress = edtSearchKeyPress
    end
    object pnl1: TPanel
      Left = 430
      Top = 16
      Width = 313
      Height = 41
      BevelOuter = bvNone
      BorderWidth = 3
      Color = clAqua
      ParentBackground = False
      TabOrder = 6
      object pnl2: TPanel
        Left = 3
        Top = 3
        Width = 307
        Height = 35
        Align = alClient
        BevelOuter = bvNone
        Caption = 'List of Missile On Resource Allocation'
        Color = 2499101
        Font.Charset = ANSI_CHARSET
        Font.Color = clWhite
        Font.Height = -19
        Font.Name = 'Deusex'
        Font.Style = []
        ParentBackground = False
        ParentFont = False
        TabOrder = 0
      end
    end
    object pnl3: TPanel
      Left = 12
      Top = 16
      Width = 313
      Height = 41
      BevelOuter = bvNone
      BorderWidth = 3
      Color = clAqua
      ParentBackground = False
      TabOrder = 7
      object pnl4: TPanel
        Left = 3
        Top = 3
        Width = 307
        Height = 35
        Align = alClient
        BevelOuter = bvNone
        Caption = 'List of available Missile'
        Color = 2499101
        Font.Charset = ANSI_CHARSET
        Font.Color = clWhite
        Font.Height = -19
        Font.Name = 'Deusex'
        Font.Style = []
        ParentBackground = False
        ParentFont = False
        TabOrder = 0
      end
    end
    object pnl5: TPanel
      Left = -6
      Top = 586
      Width = 760
      Height = 5
      BevelOuter = bvNone
      Color = clBlack
      ParentBackground = False
      TabOrder = 8
    end
  end
end
